export const WINDOW_RESIZED = "WINDOW_RESIZED";
export const MOUSE_DOWN = "MOUSE_PRESSED";
export const MOUSE_CLICK = "MOUSE_CLICKED";
export const MOUSE_UP = "MOUSE_RELEASED";
export const MOUSE_MOVE = "MOUSE_MOVED";
export const MOUSE_OVER = "MOUSE_OVER";
export const MOUSE_OUT = "MOUSE_OUT";
export const MOUSE_WHEEL = "MOUSE_WHEEL";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_SELECTED_FOOD_CATEGORY_KEY = "SET_SELECTED_FOOD_CATEGORY_KEY";
export const SET_IS_SELECTED_FOOD_ENTRY = "SET_IS_SELECTED_FOOD_ENTRY";
export const SET_FOOD_ENTRIES = "SET_FOOD_ENTRIES";
export const SET_FOOD_CATEGORIES = "SET_FOOD_CATEGORIES";

export default [
  WINDOW_RESIZED,
  MOUSE_DOWN,
  MOUSE_CLICK,
  MOUSE_UP,
  MOUSE_MOVE,
  MOUSE_OVER,
  MOUSE_OUT,
  MOUSE_WHEEL,
  SET_LANGUAGE,
  SET_SELECTED_FOOD_CATEGORY_KEY,
  SET_IS_SELECTED_FOOD_ENTRY,
  SET_FOOD_ENTRIES,
  SET_FOOD_CATEGORIES
];
